spring.application.name=api-arquitetura-example

# Server configuration
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwtSecret=minhaChaveSecretaSuperSeguraParaJWTCom64Caracteres1234567890abcdefgh
app.jwtExpirationMs=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.api_arquitetura_example=DEBUG