spring.application.name=api-arquitetura-example

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection pool
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5


## TESTES ##

# ProdutoRepositoryTest
#mvn test -Dtest=ProdutoRepositoryTest

# ProdutoServiceTest
#mvn test -Dtest=ProdutoServiceTest

# ProdutoControllerIT (Integration Test)
#mvn test -Dtest=ProdutoControllerIT

# Executar Testes Unitários - Repository e Service juntos
#mvn test -Dtest=ProdutoRepositoryTest,ProdutoServiceTest

# Executar todos os testes que terminam com "Test"
#mvn test -Dtest=*Test

# Executar apenas testes de integração
#mvn failsafe:integration-test

# Executar um IT específico
#mvn failsafe:integration-test -Dit.test=ProdutoControllerIT

# Executar Repository e Service juntos
#mvn test -Dtest=ProdutoRepositoryTest,ProdutoServiceTest

# Executar todos os testes que terminam com "Test"
#mvn test -Dtest=*Test