spring.application.name=api-arquitetura-example

#Properties
# Configurações do Banco H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true

# Logs de SQL Ativos
# Mostrar SQL no console
spring.jpa.show-sql=true

# Formatar SQL para melhor legibilidade
spring.jpa.properties.hibernate.format_sql=true

# Mostrar valores dos parâmetros (opcional)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
